### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by pelegbahar** [myspecialway/my-special-way-android#14]
Create a preliminary login screen.
UI is still TBD so create your own for now.

Send a POST request to:
https://msw-server.azurewebsites.net/login
with body:
{
"username":"msw",
"password":"Aa123456"
}
Header:
Content-Type : application/json

Response:
bearer token.
Example:
{
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1zdyIsInBhc3N3b3JkIjoiQWExMjM0NTYiLCJpYXQiOjE1MjgwMTM2MDF9.KRcUARR2DLLFO1Tau4UkgWRqNX1O_wahyR4fUkZqCAs"
}

Save the token for further use. It is needed for every request sent to the server.

requires #52

**Comment by erezak** [comment]
requires #52

**Comment by erezak** [comment]
Closed by mistake
