### ISSUE TITLE
Notification does not disappear within 10 MIN when MSW app is on background

### ISSUE THREAD

**Issue by udipo** [myspecialway/my-special-way-android#170]
Notification does not disappear within 10 MIN when MSW app is on background and screen is powered-off (dark).

Notification is stuck at least 30 MIN after it presented on mobile screen.

**Comment by udipo** [comment]
Notification does not disappear. New Notification is not presented any more … the old one is stuck on the mobile screen.

**Comment by nitzke** [comment]
notification should disappear after 15 minutes, both reminders and schedules. agreed with Leora.

**Comment by nitzke** [comment]
Hi.
It sounds like a duplicate of #192.
please retest as it shouldn't be relevant after latest changes.
Thanks
