### ISSUE TITLE
Android - New scheduler changes are not syncing to the client

### ISSUE THREAD

**Issue by okelman** [myspecialway/my-special-way-android#243]
On real time scheduler changes syncing the client gets error
see attached files

**Comment by okelman** [comment]
![68747470733a2f2f776166666c65696f2d6469726563742d75706c6f6164732d70726f64756374696f6e2e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f3563333265373437343938663035303031316630623033612f313235353136633636653832633.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c18a3d4eb69450013021e2d/125516c66e82c728ace21e0d46becccd77d5d7fedfbeec10a50ff6c62f1170257852f57d26d3e07eea142257095d1aaa455e5643feff8c2da5b13872de5b0eead16b0c72903b10aabc851cbd55bd208c4d83e0ba8e4bc5ee3e22e38d86496818501adcf85e36a39b1ece59f01fe74c52f5156065b370377b40931d77796d6420fdfa8b54d18265a3ba167c509ee5e5fc1215a27e8ec40c77605658a92834b0015d8a649b417b59e8bcc7f5114a0b1e02c8e8c3d8bdecda327423411950c620ed521805da9d54957b9567cf033b7d427d06dd19c3ff32879b91fa692d8fe1e8646b6cd60cd8cec1e7938c5a1dffb5aea683c0d73a1b4f58cb949ecc2bb905c3c9943f7bc376133e309b9ab5d8b173e9f181d8c7a4d3ba2cd913c5965b6fe5dd7ddca0f8be10c0ddd072.jpg)
![68747470733a2f2f776166666c65696f2d6469726563742d75706c6f6164732d70726f64756374696f6e2e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f3563333265373437343938663035303031316630623033612f31323535313663363665383263373.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c18a3d4eb69450013021e2d/125516c66e82c728ace21e0d46becccd77d5d7fedfbeec10a50ff6c62f1170257852f57d26d3e07eea142257095d1aaa455e5643feff8c2da5b13872de5b0eead16b0c72903b10aabc851cbd55bd208c4d83e0ba8e4bc5ee3e22e38d86496818501adcf85e36a39b1ece59f01fe74c52f5156065b370377b40931d77796d6420fdfa8b54d18265a3ba167c509ee5e5fc1215a27e8ec40c77605658a92834b0015d8a649b417b59e8bcc7f5114a0b1e02c8e8c3d8bdecda327423411950c620ed521805da9d54957b9567cf033b7d427d06dd19c3ff32879b91fa692d8fe1e8646b6cc313d89291f88b86530cbefbaea9c093d764194458c9c49ccb7deb5095c8c7367cc927403f73839aeb9bad76e8f887cfcbac94f22cd209ce90546ae7d073d0a8f8b916c4dbc03b5000.jpg)

**Comment by okelman** [comment]
![68747470733a2f2f776166666c65696f2d6469726563742d75706c6f6164732d70726f64756374696f6e2e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f3563333265373437343938663035303031316630623033612f31323535313663363665383263373.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c18a3d4eb69450013021e2d/125516c66e82c728ace21e0d46becccd77d5d7fedfbeec10a50ff6c62f1170257852f57d26d3e07eea142257095d1aaa455e5643feff8c2da5b13872de5b0eead16b0c72903b10aabc851cbd55bd208c4d83e0ba8e4bc5ee3e22e38d86496818501adcf85e36a39b1ece59f01fe74c52f5156065b370377b40931d77796d6420fdfa8b54d18265a3ba167c509ee5e5fc1215a27e8ec40c77605658a92834b0015d8a649b417b59e8bcc7f5114a0b1e02c8e8c3d8bdecda327423411950c620ed521805da9d54957b9567cf033b7d427d06dd19c3ff32879b91fa692d8fe1e8646b6cc313d89291f88b86530cbefbaea9c093d764194458c9c49ccb7deb5095c8c7367cc927403f73839aeb9bad76e8f887cfcbac94f22cd209ce90546ae7d073d0a8f8bc15cadac5395000.jpg)

**Comment by pelegbahar** [comment]
@noanika can you take a look?

**Comment by noanika** [comment]
fixed, pls test again
