### ISSUE TITLE
Lessons  have null hours  after adding medicine remainder using the portal

### ISSUE THREAD

**Issue by michalheim32** [myspecialway/my-special-way-android#248]
After create medicine remainder in the portal for a user, logout and login again in the android the result is that this user hours are getting null.

**Comment by michalheim32** [comment]
![null_Screenshot_20190123-084441_בדרכי שלי.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c32e747498f050011f0b03a/125516c66e82c728ace21e0d46e681962fbdb0aa9decba4db755ff80161477227054f27923c8b370eb162f5030b8ef4be2bfc7a3571e203b412fdbdc6df519f1c32d1d2b9c6842e8aa880dba50ec71831c86e5bd894fc4bd6b25e78adc476a1c00498ded4127e2c8159c07ab12ab1817b6192462e17c3779439c1d7525696227affad844ca.jpg)

**Comment by pelegbahar** [comment]
this is a portal issue

**Comment by michalheim32** [comment]
@pelegbahar   Can you close this  defect please , I do not have Permissions
