### ISSUE TITLE
Insert schedule data to DB

### ISSUE THREAD

**Issue by pelegbahar** [myspecialway/my-special-way-android#70]
Insert schedule data to DB for user 'student'

**Comment by TalBuch** [comment]
Done using the following mutation query:


mutation{
  updateStudent(id:"5b5ebd8c0144ac628f9de9ef",student:{
    schedule:[{
      index:"00"
      lesson:{
         title: "מפגש בוקר"
        icon: "morning"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }},
       {index:"01"
      lesson:{
        title: "ארוחת בוקר"
        icon: "breakfest-icon"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }}, 
      { index:"02"
      lesson:{
        title:"אנגלית"
        icon:"english"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }}, 
      { index:"03"
      lesson:{
        title: "בריכה"
        icon: "pool"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }}, 
      { index:"04"
      lesson:{
        title: "חשבון"
        icon: "math"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }}, 
      { index:"05"
      lesson:{
      title: "חינוך"
      icon: "education"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
      }
 		 } 
      },{
      index:"10"
      lesson:{
         title: "מפגש בוקר"
        icon: "morning"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }},
       {index:"11"
      lesson:{
        title: "ארוחת בוקר"
        icon: "breakfest-icon"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }}, 
      { index:"12"
      lesson:{
        title:"אנגלית"
        icon:"english"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }}, 
      { index:"13"
      lesson:{
        title: "בריכה"
        icon: "pool"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }}, 
      { index:"14"
      lesson:{
        title: "חשבון"
        icon: "math"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }}, 
      { index:"15"
      lesson:{
      title: "חינוך"
      icon: "education"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
      }
 		 } 
      },{
      index:"20"
      lesson:{
         title: "מפגש בוקר"
        icon: "morning"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }},
       {index:"21"
      lesson:{
        title: "ארוחת בוקר"
        icon: "breakfest-icon"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }}, 
      { index:"22"
      lesson:{
        title:"אנגלית"
        icon:"english"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }}, 
      { index:"23"
      lesson:{
        title: "בריכה"
        icon: "pool"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }}, 
      { index:"24"
      lesson:{
        title: "חשבון"
        icon: "math"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }}, 
      { index:"25"
      lesson:{
      title: "חינוך"
      icon: "education"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
      }
 		 } 
      },
    {
      index:"30"
      lesson:{
         title: "מפגש בוקר"
        icon: "morning"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }},
       {index:"31"
      lesson:{
        title: "ארוחת בוקר"
        icon: "breakfest-icon"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }}, 
      { index:"32"
      lesson:{
        title:"אנגלית"
        icon:"english"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }}, 
      { index:"33"
      lesson:{
        title: "בריכה"
        icon: "pool"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }}, 
      { index:"34"
      lesson:{
        title: "חשבון"
        icon: "math"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }}, 
      { index:"35"
      lesson:{
      title: "חינוך"
      icon: "education"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
      }
 		 } 
      },
    {
      index:"40"
      lesson:{
         title: "מפגש בוקר"
        icon: "morning"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }},
       {index:"41"
      lesson:{
        title: "ארוחת בוקר"
        icon: "breakfest-icon"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }}, 
      { index:"42"
      lesson:{
        title:"אנגלית"
        icon:"english"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }}, 
      { index:"43"
      lesson:{
        title: "בריכה"
        icon: "pool"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }}, 
      { index:"44"
      lesson:{
        title: "חשבון"
        icon: "math"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }}, 
      { index:"45"
      lesson:{
      title: "חינוך"
      icon: "education"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
      }
 		 } 
      },
    {
      index:"50"
      lesson:{
         title: "מפגש בוקר"
        icon: "morning"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }},
       {index:"51"
      lesson:{
        title: "ארוחת בוקר"
        icon: "breakfest-icon"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }}, 
      { index:"52"
      lesson:{
        title:"אנגלית"
        icon:"english"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }}, 
      { index:"53"
      lesson:{
        title: "בריכה"
        icon: "pool"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }}, 
      { index:"54"
      lesson:{
        title: "חשבון"
        icon: "math"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
        }
      }}, 
      { index:"55"
      lesson:{
      title: "חינוך"
      icon: "education"
      }
      location:{
        name:"טיטאן"
        disabled:false
        position:{
          latitude:0
          longitude:0
          floor:0
      }
 		 } 
    }]
  
  })  {
    schedule{
      index
      lesson{
        title
        icon
      }
      location{
        name
        disabled
      }
    }
  }
}
