### ISSUE TITLE
Map Management - Research and Design (client/server)

### ISSUE THREAD

**Issue by leoraperry** [myspecialway/my-special-way-android#80]
Work with server team to research and design the following:
1) How will the destinations/locations be managed in server and transferred to client?
2) How will the anchors will be linked to the locations?
3) How will blocked locations be managed? this includes not only final destinations but also corridors./paths

**Comment by pelegbahar** [comment]
Update the map:
	• Need to receive a list of nodes from the server/portal and integrate it with the unity model in the client
	• Update/block destination points - according to the node list
		○ Have a list of nodes in the building. Nodes are start-point, destination point, or passage point (such as split in corridor).
	• Client needs to provide preliminary list of nodes for the portal
	• Portal will send back (as JSON?) a list of nodes that are active/inactive


Node{
Name: string
Id: uint
Accessible: bool
Type: string  (stairs, end-point, building-entrance, corridor)
Point: string (x,y,z :float)
}


Update the model:
	• The server will provide an end point so the client can get the new 'asset-bundle' (new model)
	• JWT authentication is needed (BAU)
